# Site settings
title: Yiddish Daily
description: Daily discoveries from the Yiddish archives.
baseurl: "/yiddish-daily"
url: "https://bhaas69.github.io"

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# RSS Feed
feed:
  path: feed.xml
